### ISSUE TITLE
rake task for generating inch-badge

### ISSUE THREAD

**Issue by bijanbwb** [rrrene/inch-badge#4]
@rrrene Just wanted to say thanks _soooo_ much for your work on inch and inch-badge! I _love_ the idea of incrementally improving documentation.

I wasn't sure if this would be helpful (so feel free to close out the issue as needed), but I figured I'd share a quick and dirty rake task that I wrote to generate a new SVG inch-badge for a Rails repo.

Rather than manually passing the totals into the shell command, I basically just parsed through the results of the `inch stats` command.
### Rake Task

``` ruby
# lib/tasks/code_quality.rake
task 'generate inch badge' do
  output = `inch stats`
  a = output.partition('A:').last.partition(' objects').first.split(//).last(2).join.to_i
  b = output.partition('B:').last.partition(' objects').first.split(//).last(2).join.to_i
  c = output.partition('C:').last.partition(' objects').first.split(//).last(2).join.to_i
  u = output.partition('U:').last.partition(' objects').first.split(//).last(2).join.to_i
  Inch::Badge::Image.create('inch-badge.svg', [a, b, c, u])
  Bundler.with_clean_env { puts `mv inch-badge.svg public/` }
  puts 'Inch badge successfully generated.'
end
```
### Usage

``` shell
bundle exec rake 'generate inch badge'
```
### Ouptut

This places the new `inch-badge.svg` file into your Rails `/public` folder that you can add to your project's README file if you'd like.

Clearly it's not a perfect solution (feel free to refactor), but I figured I'd share in case this might be helpful to someone looking to do something similar.

**Comment by rrrene** [comment]
@bijanbwb Thank you so much for this. This _really_ made my day. :smiley: 

Two thoughts:
- You could use `inch stats --format=json` to get "nicer" input for the script:

``` ruby
  json = JSON[`inch stats --format=json`]
  grades = json["grade_lists"]
  a = grades["A"]
  b = grades["B"]
  # ... you get the idea
```
- Since Inch `v0.6.2` you can even use `inch suggest --format=json` to get the same numbers the badges on Inch CI are generated from.

I will keep this issue open just so other people can stumble upon it :+1:

**Comment by bijanbwb** [comment]
Awesome. Yeah that's _wayyy_ nicer, lol. You can tell I had hacked together several StackOverflow answers into those insane method chains. I was just happy to get it working, and I'm glad to hear that it might be useful to anyone else who might stumble along here. Thanks again!

_Edit: Here's the refactored version for anyone who wants to avoid the spaghetti code I originally wrote above._

``` ruby
# lib/tasks/code_quality.rake
task 'generate inch badge' do
  json = JSON[`inch stats --format=json`]
  grades = json["grade_lists"]
  a = grades["A"]
  b = grades["B"]
  c = grades["C"]
  u = grades["U"]
  Inch::Badge::Image.create('inch-badge.svg', [a, b, c, u])
  Bundler.with_clean_env { puts `mv inch-badge.svg public/` }
  puts 'Inch badge successfully generated.'
end
```

**Comment by bijanbwb** [comment]
Going to close out this issue while I'm doing a sweep of all my GitHub Issues at `https://github.com/issues` and trying to stay focused on a few projects.

Thanks again for the awesome work on inch!
